# Generated by Django 4.0.1 on 2022-02-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_rename_patient_patients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='fname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='lname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
