# Generated by Django 4.0.1 on 2022-02-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_alter_patients_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Dr_name',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Specialization',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
