# Generated by Django 4.0.1 on 2022-02-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_alter_doctor_dr_name_alter_doctor_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='pno',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
