# Generated by Django 4.0.1 on 2022-02-11 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0006_patients_pno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='age',
        ),
    ]
